In [1]:
# Importo la libreria Numpy:
import numpy as np

# Ejercicio 1:

Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [2]:
# Generamos el array aleatorio de 100 numeros entre 0 y 99:
array_aleatorio = np.random.randint (100, size = 100)
array_aleatorio

array([16, 64, 66, 42, 94, 21, 32, 11, 53, 80, 96, 49, 82, 45, 39, 88, 25,
       33, 16, 85,  6,  8,  5, 22,  4, 14, 13,  6, 25, 96, 99, 49, 16, 23,
       35, 87, 37, 21,  0, 59, 67, 84, 23, 56,  7, 84, 85, 26, 89, 20, 16,
       65, 78, 81, 72, 25, 53, 32, 42, 26, 31, 12, 70, 39, 89, 52, 23, 51,
       15, 78, 60, 87,  4, 60, 22, 74, 29, 70, 26, 45,  9, 90,  9, 98, 15,
       49, 14, 31,  4, 53, 92,  8, 11, 68, 87, 24, 52, 81, 47, 89])

In [3]:
# Calculamos la mediana del array utilizando el metodo np.median. Lo hago en una celda diferente asi queda definida la 
# variable array_aleatorio y no cambia cada ves que corro esta celda:
np.median(array_aleatorio)

42.0

In [4]:
# Como 100 es un número par, la mediana va a salir de calcular el promedio de los 2 valores que se encuentren en el medio
# del array, ordenado ascendente o descendente:
array_aleatorio_ordenado = np.sort(array_aleatorio)
array_aleatorio_ordenado

array([ 0,  4,  4,  4,  5,  6,  6,  7,  8,  8,  9,  9, 11, 11, 12, 13, 14,
       14, 15, 15, 16, 16, 16, 16, 20, 21, 21, 22, 22, 23, 23, 23, 24, 25,
       25, 25, 26, 26, 26, 29, 31, 31, 32, 32, 33, 35, 37, 39, 39, 42, 42,
       45, 45, 47, 49, 49, 49, 51, 52, 52, 53, 53, 53, 56, 59, 60, 60, 64,
       65, 66, 67, 68, 70, 70, 72, 74, 78, 78, 80, 81, 81, 82, 84, 84, 85,
       85, 87, 87, 87, 88, 89, 89, 89, 90, 92, 94, 96, 96, 98, 99])

In [5]:
# Como función de prueba voy a calcular el promedio de los 2 valores del medio del array ordenado, y verificar si es igual
# al calculado previamente. La ubicación de los 2 valores va a ser 49 y 50:
mediana = (array_aleatorio_ordenado[49] + array_aleatorio_ordenado[50])/2
if mediana == np.median(array_aleatorio):
    print('Prueba exitosa!')
else:
    print('Prueba fallida')

Prueba exitosa!


# Ejercicio 2:

Usar métodos de Numpy para calcular el factorial de un número y la suma de una serie de números (todos los números naturales entre 0 y dicho valor).

In [23]:
# Utilizo la funcion factorial para calcular factoriales:
np.math.factorial(4)

24

In [12]:
# Uso una función de prueba para confirmar si la función esta bien:
if np.math.factorial(6) == 6*5*4*3*2:
    print('Prueba exitosa!')
else:
    print('Prueba fallida')

Prueba exitosa!


In [33]:
# Creo una función que va a realizar la suma de todos los numeros naturales entre 2 valores, utilizando la función np.sum
# Primero defino la función. Los inputs a y b van a ser los valores entre los que se va a realizar la suma (incluyendo
# a y b):
def funcion(a,b):
    # luego defino una variable auxiliar aux, que va a generar el array de todos los numeros que quiero sumar:
    aux = np.array(range(a,b+1))
    # imprimo la variable auxiliar para confimar que este generando el array buscado:
    print(aux)
    # Deifno el output de la función, que va a ser la suma de todos los valores dentro de array:
    return (np.sum(aux))

In [34]:
funcion(1,3)

[1 2 3]


6

In [35]:
# Funcion de prueba para confirmar que este funcionando bien:
if funcion(2,7) == 2+3+4+5+6+7:
    print('Prueba exitosa!')
else:
    print('Prueba fallida')

[2 3 4 5 6 7]
Prueba exitosa!
